/**
 * The MapleStory map catalogue behind the burning-field map picker.
 *
 * Data comes from `public/map-data/maps.json`, generated by
 * `src/scripts/build-map-data.mjs` out of WzDataExtractor/MapExtractor - see
 * `docs/map-data.md`. It holds every *hunting* map (one with at least one
 * monster spawn point), because a burning field is a hunting map by definition:
 * towns, cutscene rooms and boss lobbies never burn.
 *
 * No React and no Supabase in here, so the search can be exercised from Node.
 */

const CATALOG_URL = "/map-data/maps.json";

/** Ceiling on rendered rows. Anything past this is noise you scroll through. */
export const MAX_RESULTS = 300;

let cache = null;
let inflight = null;

/**
 * Fetches and indexes the catalogue, once per page load.
 *
 * Every map gets a pre-lowercased haystack (name + street + region + monster
 * names + map id), because the picker filters on every keystroke over ~4,000
 * maps and rebuilding those strings each time is the only part that is slow.
 */
export async function loadMapCatalog() {
  if (cache) return cache;
  if (inflight) return inflight;

  inflight = (async () => {
    const res = await fetch(CATALOG_URL);
    if (!res.ok) throw new Error(`Could not load the map list (${res.status})`);
    const raw = await res.json();

    const maps = raw.maps.map((m) => {
      const mobNames = (m.mobs || [])
        .map((id) => raw.mobs[id]?.[0])
        .filter(Boolean);
      return {
        ...m,
        mobNames,
        _name: m.name.toLowerCase(),
        _haystack: [m.name, m.street, m.region || "", ...mobNames, String(m.id)]
          .join(" ")
          .toLowerCase(),
      };
    });

    const regions = [...new Set(maps.map((m) => m.region).filter(Boolean))].sort();

    cache = {
      generated: raw.generated,
      maps,
      regions,
      areas: buildAreas(maps),
      levelSteps: buildLevelSteps(maps),
    };
    return cache;
  })();

  try {
    return await inflight;
  } finally {
    inflight = null;
  }
}

/** Synchronous access for code that only runs after a successful load. */
export function peekMapCatalog() {
  return cache;
}

/**
 * Five-level buckets spanning whatever the catalogue actually covers.
 *
 * Derived rather than hard-coded, because the shipped regions are a build-time
 * choice (see REGIONS in build-map-data.mjs) - a level filter offering 100 and
 * 150 to somebody browsing a 260-299 catalogue is just three dead options.
 */
function buildLevelSteps(maps) {
  const levels = maps.map((m) => m.minLv).filter((l) => l != null);
  if (!levels.length) return [];
  const lo = Math.floor(Math.min(...levels) / 5) * 5;
  const hi = Math.ceil(Math.max(...maps.map((m) => m.maxLv ?? 0)) / 5) * 5;
  const steps = [];
  for (let l = lo; l <= hi; l += 5) steps.push(l);
  return steps;
}

/**
 * Areas are street names, not the world-map regions.
 *
 * `region` is what the game files the map under on the world map ("Western
 * Grandis"), and it is both too coarse to navigate by and missing on about two
 * thirds of hunting maps - every Hidden Street, mini-dungeon and event map is
 * absent from the world map entirely. `streetName` is set on essentially every
 * map and lands at roughly the granularity somebody means by "the map I train
 * on is in Geardock", so it is the browse axis; region rides along as a label.
 */
function buildAreas(maps) {
  const byStreet = new Map();

  for (const map of maps) {
    const street = map.street || "Unlisted";
    let area = byStreet.get(street);
    if (!area) {
      area = {
        street,
        region: map.region || null,
        maps: [],
        minLv: null,
        maxLv: null,
      };
      byStreet.set(street, area);
    }
    area.maps.push(map);
    if (!area.region && map.region) area.region = map.region;
    if (map.minLv != null)
      area.minLv = area.minLv == null ? map.minLv : Math.min(area.minLv, map.minLv);
    if (map.maxLv != null)
      area.maxLv = area.maxLv == null ? map.maxLv : Math.max(area.maxLv, map.maxLv);
  }

  for (const area of byStreet.values()) {
    area.maps.sort(compareMaps);
    area._haystack = `${area.street} ${area.region || ""}`.toLowerCase();
  }

  // Ordered as the progression, not alphabetically: an area list that reads
  // Cernium 260 → Hotel Arcus 265 → … → Geardock 295 is the order somebody
  // walks them in, and it puts the area you are looking for near your level.
  // Search covers lookup-by-name.
  return [...byStreet.values()].sort(
    (a, b) =>
      (a.minLv ?? Infinity) - (b.minLv ?? Infinity) ||
      a.street.localeCompare(b.street),
  );
}

/**
 * Reading order inside an area: by level, then by name.
 *
 * Areas are built as progressions - Robot Depot 1 through 8 climb from 297 to
 * 298 - so level ordering is the order you walk them in. Names tie-break, and
 * "Robot Depot 10" has to sort after "Robot Depot 9" rather than after 1, hence
 * the numeric collation.
 */
const collator = new Intl.Collator(undefined, { numeric: true });

export function compareMaps(a, b) {
  const al = a.minLv ?? Infinity;
  const bl = b.minLv ?? Infinity;
  if (al !== bl) return al - bl;
  return collator.compare(a.name, b.name);
}

/**
 * Matches, best first.
 *
 * A name that *starts* with what was typed is what was being looked for, a name
 * that merely contains it is second, and everything else matched on street,
 * region, monster or map id. Within a tier the level ordering above applies, so
 * a search for "robot depot" reads 1, 2, 3… instead of shuffling.
 */
export function searchMaps(maps, query) {
  const q = query.trim().toLowerCase();
  if (!q) return [];

  const scored = [];
  for (const map of maps) {
    if (!map._haystack.includes(q)) continue;
    const tier = map._name.startsWith(q) ? 0 : map._name.includes(q) ? 1 : 2;
    scored.push({ map, tier });
  }

  scored.sort((a, b) => a.tier - b.tier || compareMaps(a.map, b.map));
  return scored.map((s) => s.map);
}

/** Levels are a range only when the monsters in the map differ. */
export function formatLevelRange(map) {
  if (map.minLv == null) return null;
  return map.minLv === map.maxLv ? `Lv ${map.minLv}` : `Lv ${map.minLv}-${map.maxLv}`;
}

/**
 * The one-line "what is this place" summary under a map's name.
 *
 * `omitStreet` is for the browse view, where every row in the list is already in
 * the street named at the top of it and repeating it 25 times says nothing.
 * `omitRegion` is the same argument for a catalogue built from one region: the
 * modal says "Western Grandis" once in its header instead of on all 168 rows.
 */
export function describeMap(map, { omitStreet = false, omitRegion = false } = {}) {
  const parts = [];
  if (map.street && !omitStreet) parts.push(map.street);
  if (map.region && !omitRegion && map.region !== map.street) parts.push(map.region);
  if (map.mobNames?.length) parts.push(map.mobNames.slice(0, 3).join(", "));
  return parts.join(" · ");
}
